export let birds= [
"Cassin's Finch",
"Limpkin",
"Rupornis magnirostris",
"Blue Jay",
"Steller's Jay",
"Balearica regulorum",
"Scarlet Flycatcher",
"American Avocet",
"Ardeotis kori",
"Yellow-billed Magpie",
"Canada Jay",
"Sandhill Crane",
"Northern Waterthrush",
"Ardea herodias occidentalis",
"Sora",
"Anas platyrhynchos diazi",
"Grey Wagtail",
"Pacific-slope Flycatcher",
"Least Flycatcher",
"Buff-breasted Flycatcher",
"Willow Flycatcher",
"Hammond's Flycatcher",
"Empidonax occidentalis",
"Virginia Rail",
"Common Crane",
"Boat-tailed Grackle",
"Barnacle Goose",
"Cyanocorax yucatanicus",
"Cyanocorax yncas",
"Wilson's Storm Petrel",
"Quiscalus niger",
"Brown Jay",
"Megarynchus pitangua",
"Gallinula tenebrosa",
"Gallus gallus domesticus",
"Helmeted Guineafowl",
"Junco hyemalis caniceps",
"Cassin's Kingbird",
"Eastern Kingbird",
"Scissor-tailed Flycatcher",
"Thick-billed Kingbird",
"Western Kingbird",
"Fork-tailed Flycatcher",
"Gallirallus australis",
"Calocitta formosa",
"Calocitta colliei",
"American Coot",
"Rose-throated Becard",
"Rough-legged Buzzard",
"Black Swan",
"Philesturnus rufusater",
"Great Black-backed Gull",
"Great Kiskadee",
"American Black Duck",
"Anthus novaeseelandiae novaeseelandiae",
"Eastern Phoebe",
"Black Phoebe",
"Tityra semifasciata",
"Dryocopus lineatus",
"Porphyrio melanotus",
"Anas bahamensis",
"Egretta novaehollandiae",
"Anas crecca carolinensis",
"Chukar Partridge",
"Least Grebe",
"Bell's Sparrow",
"Red Junglefowl",
"Pyrrhuloxia",
"Northern Cardinal",
"Lincoln's Sparrow",
"Pied-billed Grebe",
"Swamp Sparrow",
"Wild Turkey",
"Meleagris ocellata",
"Willow Ptarmigan",
"Black-chinned Sparrow",
"Alpine Chough",
"Brewer's Sparrow",
"Mountain Bluebird",
"Field Sparrow",
"Anas superciliosa",
"Red Fox Sparrow",
"Phoenicopterus ruber",
"Eurasian Blackcap",
"Bell's Vireo",
"Vireo plumbeus",
"Philadelphia Vireo",
"Yellow-throated Vireo",
"Red-eyed Vireo",
"Harris's Sparrow",
"Hutton's Vireo",
"White-throated Sparrow",
"Golden-crowned Sparrow",
"Yellowhammer",
"Barrow's Goldeneye",
"Common Reed Bunting",
"Warbling Vireo",
"European Serin",
"Serinus mozambicus",
"Kalij Pheasant",
"Euphonia elegantissima",
"Euphonia hirundinacea",
"Euphonia affinis",
"Tricolored Blackbird",
"Momotus lessonii",
"Warbling White-eye",
"Pelagic Cormorant",
"Hooded Oriole",
"Audubon's Oriole",
"African Pied Wagtail",
"Anas superciliosa Ã— platyrhynchos",
"Streak-backed Oriole",
"Altamira Oriole",
"Carduelis cannabina",
"Grey-cheeked Thrush",
"White-breasted Waterhen",
"Pavo cristatus",
"Rallus crepitans",
"Nestor meridionalis septentrionalis",
"Green-tailed Towhee",
"Spotted Towhee",
"Eastern Towhee",
"Cairina moschata domestica",
"Phalacrocorax varius",
"Picoides dorsalis",
"Nuttall's Woodpecker",
"Ladder-backed Woodpecker",
"Gambel's Quail",
"Eurasian Bullfinch",
"Neotropic Cormorant",
"Downy Woodpecker",
"Northern Bobwhite",
"Cinnamon-rumped Seedeater",
"Hairy Woodpecker",
"Semipalmated Sandpiper",
"Black-backed Woodpecker",
"Greater Scaup",
"Red-billed Tropicbird",
"Eastern Meadowlark",
"Budgerigar",
"Lesser Scaup",
"Aythya novaeseelandiae",
"Montezuma Quail",
"Brown Pelican",
"White-throated Dipper",
"Chen rossii",
"California Quail",
"Common Grackle",
"Great-tailed Grackle",
"Scaled Quail",
"Pileated Woodpecker",
"Blue Grosbeak",
"Berylline Hummingbird",
"Common Yellowthroat",
"Trogon melanocephalus",
"Common Whitethroat",
"Pine Grosbeak",
"Coccothraustes vespertinus",
"Hawfinch",
"Golden-winged Warbler",
"Opisthocomus hoazin",
"Setophaga coronata coronata",
"Diglossa baritula",
"Saltator coerulescens",
"Saltator atriceps",
"Sicalis flaveola",
"Mandarin Duck",
"Junco hyemalis hyemalis",
"Eupsittula canicularis",
"Microcarbo melanoleucos",
"Summer Tanager",
"Scarlet Tanager",
"Piranga flava",
"Black-throated Sparrow",
"Larus dominicanus",
"Piaya cayana",
"Rufous-crowned Sparrow",
"Lewis's Woodpecker",
"Gila Woodpecker",
"Savannah Sparrow",
"Melanerpes pucherani",
"Rock Wren",
"Red-bellied Woodpecker",
"Melanerpes chrysogenys",
"Acorn Woodpecker",
"Northern Flicker",
"Rufous-capped Warbler",
"Yellow-legged Gull",
"Ramphocelus passerinii",
"Burrowing Owl",
"Cackling Goose",
"Brambling",
"Common Chaffinch",
"Dark-eyed Junco",
"Common Cuckoo",
"Yellow-eyed Junco",
"Nelson's Sparrow",
"Grasshopper Sparrow",
"Seaside Sparrow",
"Black-billed Cuckoo",
"Mangrove Cuckoo",
"Yellow-billed Cuckoo",
"Clark's Nutcracker",
"Groove-billed Ani",
"Vesper Sparrow",
"Olive Sparrow",
"Greater Roadrunner",
"Geococcyx velox",
"Bananaquit",
"Painted Bunting",
"Alectura lathami",
"Passerina leclancherii",
"Lazuli Bunting",
"Yellow-breasted Chat",
"Crax rubra",
"Penelope purpurascens",
"Copsychus malabaricus",
"Paroaria capitata",
"Cyanerpes cyaneus",
"Microcarbo melanoleucos brevirostris",
"Williamson's Sapsucker",
"Rose-breasted Grosbeak",
"Red-breasted Sapsucker",
"Black-headed Grosbeak",
"Red-naped Sapsucker",
"Ortalis poliocephala",
"Plain Chachalaca",
"Pied Crow",
"Black-and-white Warbler",
"Volatinia jacarina",
"Thraupis palmarum",
"Momotus mexicanus",
"Brewer's Blackbird",
"Cacatua galerita",
"Junco hyemalis oreganus",
"Pacific Golden Plover",
"Bronzed Cowbird",
"Brown-headed Cowbird",
"Merops pusillus",
"European Bee-eater",
"Pteroglossus torquatus",
"Red Crossbill",
"Green Bee-eater",
"Two-barred Crossbill",
"European Roller",
"Coracias caudatus",
"Indian Roller",
"Yellow-headed Blackbird",
"Lark Sparrow",
"Bobolink",
"Western Osprey",
"Phainopepla",
"Couch's Kingbird",
"Common Chiffchaff",
"Circus cyaneus hudsonius",
"Grallina cyanoleuca",
"Snow Bunting",
"Lark Bunting",
"Ruby-crowned Kinglet",
"Common Firecrest",
"Goldcrest",
"Golden-crowned Kinglet",
"Tropical Kingbird",
"Pelecanus conspicillatus",
"Aulacorhynchus prasinus",
"Todiramphus sanctus",
"Bullock's Oriole",
"Dickcissel",
"Grey Kingbird",
"Black Tern",
"Oriturus superciliosus",
"Psarocolius montezuma",
"Fieldfare",
"Notiomystis cincta",
"Sagittarius serpentarius",
"Rose-ringed Parakeet",
"Platycercus eximius",
"Prothonotary Warbler",
"Ringed Kingfisher",
"Nestor meridionalis",
"Red-crowned Amazon",
"Amazona albifrons",
"Amazona oratrix",
"Whinchat",
"Ara militaris",
"American Tree Sparrow",
"Pied Kingfisher",
"Chloroceryle aenea",
"Chloroceryle amazona",
"Myiozetetes similis",
"Curve-billed Thrasher",
"Belted Kingfisher",
"Horned Lark",
"Alisterus scapularis",
"Cinnyris jugularis",
"Xiphorhynchus flavigaster",
"Jacana jacana",
"Red Phalarope",
"European Turtle Dove",
"Pica hudsonia",
"Hooded Crow",
"Monk Parakeet",
"Eurasian Collared Dove",
"Western Tanager",
"Least Bittern",
"Verdin",
"MacGillivray's Warbler",
"Rock Dove",
"Hooded Warbler",
"Cerulean Warbler",
"Common Wood Pigeon",
"Piranga bidentata",
"White-crowned Pigeon",
"Band-tailed Pigeon",
"Red-billed Pigeon",
"Prairie Warbler",
"Common Nighthawk",
"Lesser Nighthawk",
"Eurasian Spoonbill",
"Common Poorwill",
"House Finch",
"Purple Finch",
"Pauraque",
"Campephilus guatemalensis",
"Brown Thrasher",
"White-tipped Dove",
"Nyctibius jamaicensis",
"Anas penelope",
"Buteo plagiatus",
"Calliope Hummingbird",
"Western Screech Owl",
"Porphyrio poliocephalus",
"Eastern Screech Owl",
"Zenaida auriculata",
"Hymenolaimus malacorhynchos",
"Black-throated Blue Warbler",
"Northern Beardless Tyrannulet",
"Caracara plancus",
"Common Ground Dove",
"Eupsittula nana",
"Nestor notabilis",
"Ruddy Ground Dove",
"Geopelia striata",
"Little Owl",
"Smooth-billed Ani",
"Eastern Bluebird",
"African Spoonbill",
"Great Horned Owl",
"Cave Swallow",
"Purple Martin",
"Setophaga coronata auduboni",
"Hirundo neoxena",
"Barn Swallow",
"Surfbird",
"Ruff",
"Platalea regia",
"Violet-green Swallow",
"Bostrychia hagedash",
"Sand Martin",
"American White Ibis",
"Glossy Ibis",
"White-faced Ibis",
"Northern Raven",
"Northern Rough-winged Swallow",
"Masked Booby",
"Red-footed Booby",
"Brown Booby",
"Morus serrator",
"Eudyptula minor",
"Megadyptes antipodes",
"Hamerkop",
"Eurasian Wren",
"Red Knot",
"Red-backed Shrike",
"Baird's Sandpiper",
"Meleagris gallopavo intermedia",
"Western Sandpiper",
"Purple Sandpiper",
"Dunlin",
"Curlew Sandpiper",
"Pectoral Sandpiper",
"Short-billed Dowitcher",
"Malurus cyaneus",
"Common Greenshank",
"Todiramphus sanctus vagans",
"Green Sandpiper",
"Wood Sandpiper",
"Greater Yellowlegs",
"Lesser Yellowlegs",
"Eurasian Curlew",
"Eurasian Whimbrel",
"Phalacrocorax carbo novaehollandiae",
"Petroica macrocephala macrocephala",
"Petroica australis longipes",
"Prosthemadera novaeseelandiae novaeseelandiae",
"Short-eared Owl",
"Rhipidura fuliginosa fuliginosa",
"American Woodcock",
"Ruddy Turnstone",
"Black Turnstone",
"Rhipidura fuliginosa placabilis",
"Black-tailed Godwit",
"Hudsonian Godwit",
"Marbled Godwit",
"Red-necked Phalarope",
"Upland Sandpiper",
"Bar-tailed Godwit",
"Northern Saw-whet Owl",
"Common Sandpiper",
"Trichoglossus haematodus",
"Northern Hawk-Owl",
"Blue-grey Gnatcatcher",
"Chipping Sparrow",
"Red-whiskered Bulbul",
"Indigo Bunting",
"Varied Bunting",
"Manorina melanocephala",
"Ocyphaps lophotes",
"Jabiru",
"Red-vented Bulbul",
"Anser cygnoides domesticus",
"European Green Woodpecker",
"Black-footed Albatross",
"Common Ostrich",
"Laysan Albatross",
"Northern Fulmar",
"Grey Francolin",
"Broad-billed Hummingbird",
"Black-necked Grebe",
"Great Crested Grebe",
"Horned Grebe",
"Great Spotted Woodpecker",
"Red-necked Grebe",
"Little Grebe",
"Mountain Plover",
"Double-crested Cormorant",
"Great Cormorant",
"Brandt's Cormorant",
"Clark's Grebe",
"Great White Pelican",
"American White Pelican",
"Mourning Dove",
"Vanellus miles",
"Western Gull",
"Trogon massena",
"Larus thayeri",
"Heermann's Gull",
"Yellow-footed Gull",
"Mew Gull",
"Iceland Gull",
"Ring-billed Gull",
"Trogon collaris",
"White-winged Dove",
"Lesser Black-backed Gull",
"California Gull",
"Prosthemadera novaeseelandiae",
"Elegant Trogon",
"Glaucous-winged Gull",
"Trogon citreolus",
"Pigeon Guillemot",
"Himantopus leucocephalus",
"Black Guillemot",
"Anthornis melanura",
"Marabou Stork",
"Threskiornis moluccus",
"Thraupis episcopus",
"White-tailed Hawk",
"Arctic Tern",
"Common Tern",
"Forster's Tern",
"Great Grey Shrike",
"Pharomachrus mocinno",
"Sterna striata",
"Parasitic Jaeger",
"Pomarine Jaeger",
"Anas gracilis",
"Black-legged Kittiwake",
"Black Skimmer",
"Razorbill",
"Atlantic Puffin",
"Tufted Puffin",
"Common Blackbird",
"Turdus plumbeus",
"Clay-colored Thrush",
"American Robin",
"Mistle Thrush",
"Rhinoceros Auklet",
"Song Thrush",
"Galbula ruficauda",
"Northern Jacana",
"European Stonechat",
"Eurasian Hoopoe",
"Rusty Blackbird",
"Pacific Loon",
"Mimus gilvus",
"Passer italiae",
"Common Loon",
"Red-throated Loon",
"Northern Wheatear",
"Magnificent Frigatebird",
"Great Frigatebird",
"Eurasian Hobby",
"Prairie Falcon",
"Aplomado Falcon",
"Peregrine Falcon",
"Falco rufigularis",
"American Kestrel",
"Strix varia",
"Merlin",
"Common Moorhen",
"Wilson's Warbler",
"Swainson's Thrush",
"Falco novaeseelandiae",
"Hermit Thrush",
"Veery",
"Northern Crested Caracara",
"Herpetotheres cachinnans",
"Lapland Longspur",
"Milvago chimachima",
"White Stork",
"Wood Stork",
"Yellow-billed Stork",
"Western Bluebird",
"Ephippiorhynchus senegalensis",
"Turkey Vulture",
"Townsend's Solitaire",
"Cathartes burrovianus",
"Sarcoramphus papa",
"Black Vulture",
"Great Grey Owl",
"Anastomus lamelligerus",
"Grey Plover",
"California Condor",
"Spotted Flycatcher",
"Killdeer",
"Wilson's Plover",
"Piping Plover",
"Common Redstart",
"Black Redstart",
"Little Ringed Plover",
"Eumomota superciliosa",
"Anas querquedula",
"Black-necked Stilt",
"Black Oystercatcher",
"Eurasian Magpie",
"Eurasian Oystercatcher",
"Haematopus unicolor",
"Northern Lapwing",
"Spur-winged Lapwing",
"Vanellus armatus",
"Bluethroat",
"Inca Dove",
"Pied Avocet",
"Common Pheasant",
"American Golden Plover",
"American Dipper",
"European Robin",
"Melanerpes aurifrons",
"Common Ringed Plover",
"Western Reef Heron",
"Little Blue Heron",
"Tricolored Heron",
"Snowy Egret",
"Little Egret",
"Pacific Reef Heron",
"Blue Rock Thrush",
"Ardea cocoi",
"Grey Heron",
"Great Blue Heron",
"Black-crowned Night Heron",
"Rufous-backed Thrush",
"Squacco Heron",
"Yellow-crowned Night Heron",
"Aramides cajaneus",
"Western Cattle Egret",
"Green Heron",
"Porphyrio martinicus",
"American Bittern",
"Cochlearius cochlearius",
"Anhinga novaehollandiae",
"African Darter",
"Melozone fusca",
"Golden Eagle",
"Wood Thrush",
"Aphelocoma wollweberi",
"Accipiter striatus",
"Eurasian Sparrowhawk",
"Northern Goshawk",
"Reddish Egret",
"Common Goldeneye",
"Brown Noddy",
"Spotted Sandpiper",
"Purple Heron",
"Collared Kingfisher",
"Whooping Crane",
"Black-winged Stilt",
"Mountain Pygmy Owl",
"Circus approximans",
"Western Marsh Harrier",
"Phalacrocorax sulcirostris",
"Zone-tailed Hawk",
"Striated Heron",
"Platalea ajaja",
"Short-tailed Hawk",
"Great Egret",
"Swainson's Hawk",
"Red-legged Partridge",
"Red-shouldered Hawk",
"Red-tailed Hawk",
"Snowy Plover",
"Wandering Tattler",
"Willet",
"Bateleur",
"Wilson's Snipe",
"Common Black Hawk",
"Bonaparte's Gull",
"Short-toed Snake Eagle",
"Chroicocephalus novaehollandiae",
"Black-headed Gull",
"Laughing Gull",
"Franklin's Gull",
"Sooty Tern",
"Least Tern",
"Caspian Tern",
"Royal Tern",
"Greater Crested Tern",
"White-tailed Kite",
"Egyptian Goose",
"Streptopelia senegalensis",
"Gerygone igata",
"Bald Eagle",
"Grass Wren",
"African Fish Eagle",
"Snowy Owl",
"Ciccaba virgata",
"Ruffed Grouse",
"Busarellus nigricollis",
"Snail Kite",
"Red Kite",
"Griffon Vulture",
"European Pied Flycatcher",
"Momotus coeruliceps",
"Semipalmated Plover",
"Brahminy Kite",
"White-backed Vulture",
"Mississippi Kite",
"Dives dives",
"Baeolophus atricristatus",
"Tufted Titmouse",
"Oak Titmouse",
"Song Sparrow",
"Eurasian Siskin",
"White Wagtail",
"Brown Creeper",
"Bucorvus leadbeateri",
"Meadow Pipit",
"Buff-bellied Pipit",
"Tachycineta albilinea",
"Carolina Chickadee",
"Black-capped Chickadee",
"Mountain Chickadee",
"Chestnut-backed Chickadee",
"Coal Tit",
"Chlorophanes spiza",
"Common Waxbill",
"Eurasian Blue Tit",
"Yellow-bellied Sapsucker",
"American Cliff Swallow",
"Troglodytes pacificus",
"Winter Wren",
"Eurasian Tree Sparrow",
"House Sparrow",
"Aphelocoma californica",
"Buff-bellied Hummingbird",
"Amazilia tzacatl",
"Dicrurus adsimilis",
"Violet-crowned Hummingbird",
"Scaly-breasted Munia",
"Tigrisoma mexicanum",
"Porphyrio melanotus melanotus",
"Black Scoter",
"Clay-colored Sparrow",
"Amazilia rutila",
"Zenaida Dove",
"Dunnock",
"Common Kestrel",
"Varied Thrush",
"Ruby-throated Hummingbird",
"Blue-throated Mountaingem",
"Dusky-capped Flycatcher",
"American Redstart",
"Brown-crested Flycatcher",
"Zosterops lateralis",
"White-crowned Sparrow",
"Red-winged Blackbird",
"Great Tit",
"Zonotrichia capensis",
"Oreothlypis peregrina",
"Oreothlypis celata",
"Oreothlypis ruficapilla",
"Mourning Warbler",
"Kentucky Warbler",
"Cape May Warbler",
"Northern Parula",
"Magnolia Warbler",
"Bay-breasted Warbler",
"Blackburnian Warbler",
"Setophaga petechia",
"Blackpoll Warbler",
"Palm Warbler",
"Pine Warbler",
"Myrtle Warbler",
"Yellow-throated Warbler",
"Campylopterus hemileucurus",
"Vireo cassinii",
"Black-throated Grey Warbler",
"Townsend's Warbler",
"Hermit Warbler",
"Golden-cheeked Warbler",
"Black-throated Green Warbler",
"Canada Warbler",
"Cardellina rubra",
"Florida Scrub Jay",
"Red-headed Woodpecker",
"Corn Bunting",
"Common Redpoll",
"Pine Siskin",
"Thraupis abbas",
"Lesser Goldfinch",
"Lawrence's Goldfinch",
"American Goldfinch",
"African Sacred Ibis",
"White Tern",
"Tree Swallow",
"Larus dominicanus dominicanus",
"Java Sparrow",
"American Oystercatcher",
"European Greenfinch",
"Cooper's Hawk",
"Blue-headed Vireo",
"Broad-tailed Hummingbird",
"Chroicocephalus scopulinus",
"Western Grebe",
"Hemiphaga novaeseelandiae",
"Sabine's Gull",
"Ramphastos sulfuratus",
"Dacelo novaeguineae",
"Eurasian Coot",
"Hirundo rustica erythrogaster",
"Costa's Hummingbird",
"Anna's Hummingbird",
"Colaptes auratus cafer",
"Blue-footed Booby",
"Oriental Magpie-Robin",
"Allen's Hummingbird",
"Rufous Hummingbird",
"Lucifer Sheartail",
"Common Bulbul",
"Larus glaucescens Ã— occidentalis",
"Aphelocoma woodhouseii",
"Florisuga mellivora",
"Haematopus finschi",
"Spruce Grouse",
"Black-chinned Hummingbird",
"Hen Harrier",
"Ardea alba modesta",
"Great Crested Flycatcher",
"Ferruginous Hawk",
"White-throated Swift",
"Vaux's Swift",
"Chimney Swift",
"Chestnut-sided Warbler",
"Loggerhead Shrike",
"Anhinga",
"Common Myna",
"Pygmy Nuthatch",
"Actophilornis africanus",
"Red-breasted Nuthatch",
"Eurasian Nuthatch",
"Brown-headed Nuthatch",
"Common Swift",
"Common Starling",
"Ovenbird",
"Western Yellow Wagtail",
"White-eyed Vireo",
"Long-billed Thrasher",
"Sanderling",
"California Thrasher",
"Common Gallinule",
"Stilt Sandpiper",
"Rivoli's Hummingbird",
"Black-vented Oriole",
"Scott's Oriole",
"Broad-winged Hawk",
"Common Snipe",
"Orchard Oriole",
"Least Sandpiper",
"Grey Catbird",
"Porphyrio hochstetteri",
"White-rumped Sandpiper",
"Wilson's Phalarope",
"Colaptes auratus auratus",
"Melanotis caerulescens",
"Tiaris olivaceus",
"Sage Thrasher",
"Long-billed Dowitcher",
"Solitary Sandpiper",
"White-breasted Nuthatch",
"Common Redshank",
"Black-bellied Whistling Duck",
"White-faced Whistling Duck",
"Fulvous Whistling Duck",
"Icterus abeillei",
"Vanellus chilensis",
"Trumpeter Swan",
"Whooper Swan",
"Tundra Swan",
"Mute Swan",
"Baltimore Oriole",
"Mallard",
"Northern Pintail",
"Eurasian Teal",
"Anas cyanoptera",
"Mottled Duck",
"Anas discors",
"Anas strepera",
"Anas clypeata",
"Anas chlorotis",
"Rhipidura leucophrys",
"Anas americana",
"Bufflehead",
"Red-breasted Merganser",
"Common Merganser",
"Greylag Goose",
"Greater White-fronted Goose",
"Common Eider",
"Rallus obsoletus",
"Platycercus elegans",
"Velvet Scoter",
"Black Kite",
"Gull-billed Tern",
"Ninox novaeseelandiae novaeseelandiae",
"Surf Scoter",
"Ring-necked Duck",
"Common Pochard",
"Tufted Duck",
"Long-billed Curlew",
"Chen caerulescens",
"Wrentit",
"Canada Goose",
"Elegant Tern",
"Branta sandvicensis",
"Redhead",
"Wood Duck",
"Hooded Merganser",
"Harlequin Duck",
"Aratinga nenday",
"Psittacara holochlorus",
"Muscovy Duck",
"Red-crested Pochard",
"Psittacara erythrogenys",
"Say's Phoebe",
"Canvasback",
"Picoides albolarvatus",
"Blue-winged Warbler",
"Northwestern Crow",
"Long-eared Owl",
"American Crow",
"Long-tailed Duck",
"Chenonetta jubata",
"Sandwich Tern",
"Eolophus roseicapilla",
"Colaptes rubiginosus",
"Meleagris gallopavo silvestris",
"Ptiliogonys cinereus",
"Swallow-tailed Kite",
"European Goldfinch",
"Cassiculus melanicterus",
"Dendragapus fuliginosus",
"American Bushtit",
"Long-tailed Tit",
"Zosterops lateralis lateralis",
"Haliaeetus leucogaster",
"Common Murre",
"Tringa semipalmata inornatus",
"Eurasian Skylark",
"Crested Lark",
"Common House Martin",
"Worm-eating Warbler",
"Hylocharis leucotis",
"Northern Mockingbird",
"Gymnorhina tibicen",
"Common Kingfisher",
"Streptopelia chinensis",
"Cedar Waxwing",
"Bohemian Waxwing",
"Common Shelduck",
"Petroica australis australis",
"Amazona autumnalis",
"Dusky Grouse",
"Canyon Wren",
"Ruddy Shelduck",
"Cactus Wren",
"Campylorhynchus rufinucha",
"Rhipidura fuliginosa",
"Black-tailed Gnatcatcher",
"Pelecanus occidentalis carolinensis",
"Abert's Towhee",
"Melozone crissalis",
"Carolina Wren",
"Harris's Hawk",
"Anas platyrhynchos domesticus",
"Troglodytes aedon",
"Buteo lineatus elegans",
"Thamnophilus doliatus",
"Bewick's Wren",
"Tadorna variegata",
"Slate-throated Whitestart",
"Phalacrocorax varius varius",
"Painted Whitestart",
"Larus argentatus smithsonianus",
"Louisiana Waterthrush",
"Sula granti",
"Ara macao",
"Peucaea ruficauda",
"Buff-breasted Sandpiper",
"Greater Flamingo",
"Northern Gannet",
"Pelecanus occidentalis californicus",
"Ferruginous Pygmy Owl",
"Ruddy Duck",
"Ash-throated Flycatcher",
"Green Kingfisher",
"Western Meadowlark",
"Ramphastos ambiguus",
"Paroaria coronata",
"Common Buzzard",
"Sulphur-bellied Flycatcher",
"Western Wood Pewee",
"Carrion Crow",
"Cyanoramphus novaezelandiae",
"Eastern Wood Pewee",
"Greater Pewee",
"Olive-sided Flycatcher",
"European Herring Gull",
"White-throated Kingfisher",
"Onychognathus morio",
"Blue Bunting",
"Marsh Wren",
"Western Barn Owl",
"Trogon caligatus",
"Corvus monedula",
"Fish Crow",
"Spheniscus demersus",
"Rook",
"House Crow",
"Brant Goose",
"Glaucous Gull",
"Columba livia domestica",
"Eurasian Jay",
"Anser anser domesticus",
"Mitrephanes phaeocercus",
"Pink-footed Shearwater",
"Great Shearwater"
]